name: Windows Push Test
on: [ push, pull_request ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Get short commit hash
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Test mgpp
        run: |
          .\gradlew.bat :main:test

      - name: Build mgpp
        run: |
          .\gradlew.bat :main:publishToMavenLocal --info

      - name: Set Android SDK tools
        run: echo "$ANDROID_HOME/build-tools/30.0.3" >> $GITHUB_PATH

      - name: Test Kotlin DSl
        run : |
          cd TestProjectKt
          .\gradlew.bat :deploy --info
          .\gradlew.bat :antiAlias --info
          cd ..

      - name: Test Groovy DSl
        run : |
          cd TestProjectGroovy
          .\gradlew.bat :deploy --info
          .\gradlew.bat :antiAlias --info
          cd ..

      - name: Test Multi-Project
        run : |
          cd TestMultiproject
          .\gradlew.bat :main:deploy --info
          cd ..

      - uses: actions/upload-artifact@v3
        with:
          name: mgpp-snapshot-build
          path: |
            build/libs/*.jar
            TestProjectGroovy/build/tmp/deploy/*.jar
            TestProjectKt/build/tmp/deploy/*.jar
            TestMultiproject/build/tmp/deploy/*.jar